import type { Metadata } from "next";
import { GraphieRegular, GraphieExtraBold } from "@/fonts/fonts";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScrollWrapper from "@/components/ui/SmothScrollWrapper";
import AOSInit from "@/components/AousInit";

export const metadata: Metadata = {
  title: "Tenpo",
  description: "Generated by TMGC",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${GraphieRegular.variable} ${GraphieExtraBold.variable}`}
    >
      <body
        className={`antialiased ${GraphieRegular.variable} ${GraphieExtraBold.variable}`}
      >
        {/* Fondo animado global */}
        <div className="fixed inset-0 -z-10 animated-gradient" />
        <AOSInit />
        {/* Contenido con scroll suave */}
        <SmoothScrollWrapper>
          <Navbar />
          {children}
          <div className=" p-4">
            <Footer />
          </div>
        </SmoothScrollWrapper>
      </body>
    </html>
  );
}
